### PR TITLE
perf: fix release merge

### PR DESCRIPTION
**Pull request by kgracki**

### CODE REVIEW

**Comment by kgracki** [comment]
hey guys, I tested it on akord-data and looks fine so I believe it should also do the trick here
image

**Comment by kgracki** [comment]
not sure if merge directly to master as a hotfix or do we want to release the js soon?

**Comment by wkolod** [comment]
we may need to bump `package.json` version to the latest tag `5.0.2` before merging

**Comment by kgracki** [comment]
hey @wkolod good catch, thanks! I'll close this PR and make another to main then + bump package.json

**Pull request closed without merging**
